### ISSUE TITLE
gen-conf error

### ISSUE THREAD

**Issue by Yurchenko** [criteo/kerberos-docker#16]
trying to 'make gen-conf' :

```
/usr/bin/make -f /Users/mac/repos/kerberos-docker/Makefile -C /Users/mac/repos/kerberos-docker gen-conf
=== get environment variables ===
.env.values
...OK
=== build python virtual environment ===
Requirement already satisfied: pip in ./.venv/lib/python3.11/site-packages (24.0)
Requirement already satisfied: Jinja2==3.1.2 in ./.venv/lib/python3.11/site-packages (from -r ./requirements.txt (line 9)) (3.1.2)
Requirement already satisfied: glob2==0.6 in ./.venv/lib/python3.11/site-packages (from -r ./requirements.txt (line 10)) (0.6)
Requirement already satisfied: MarkupSafe>=2.0 in ./.venv/lib/python3.11/site-packages (from Jinja2==3.1.2->-r ./requirements.txt (line 9)) (2.1.5)
Quit with deactivate command...
=== generate docker compose configuration ubuntu-example.com ===
=== copy template directory to ./build-template to ./build-ubuntu-example.com ===
=== remove existing ./build-ubuntu-example.com ====
=== generate template configuration for ./build ===
Traceback (most recent call last):
  File "/Users/mac/repos/kerberos-docker/./script/generate_from_template.py", line 112, in <module>
    for template_path in glob2.glob(f"./{build_name}/**/*.template", recursive=True):
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/repos/kerberos-docker/.venv/lib/python3.11/site-packages/glob2/impl.py", line 60, in glob
    return list(self.iglob(pathname, with_matches, include_hidden,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/repos/kerberos-docker/.venv/lib/python3.11/site-packages/glob2/impl.py", line 126, in _iglob
    for dirname, dir_groups in dirs:
  File "/Users/mac/repos/kerberos-docker/.venv/lib/python3.11/site-packages/glob2/impl.py", line 127, in _iglob
    for name, groups in self.resolve_pattern(dirname, basename,
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/repos/kerberos-docker/.venv/lib/python3.11/site-packages/glob2/impl.py", line 186, in resolve_pattern
    return fnmatch.filter(names, pattern, norm_paths, case_sensitive, sep)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/repos/kerberos-docker/.venv/lib/python3.11/site-packages/glob2/fnmatch.py", line 87, in filter
    match = _compile_pattern(pat, case_sensitive)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/repos/kerberos-docker/.venv/lib/python3.11/site-packages/glob2/fnmatch.py", line 80, in _compile_pattern
    return re.compile(res, flags).match
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/__init__.py", line 227, in compile
    return _compile(pattern, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/_compiler.py", line 743, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/_parser.py", line 982, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/_parser.py", line 457, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/re/_parser.py", line 843, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 6
make: *** [gen-conf] Error 1

Process finished with exit code 2
```

**Comment by elfmacs** [comment]
same here ：

=== get environment variables ===
removed '.env.values'
...OK
=== build python virtual environment ===
Requirement already satisfied: pip in ./.venv/lib/python3.11/site-packages (24.0)
Requirement already satisfied: Jinja2==3.1.2 in ./.venv/lib/python3.11/site-packages (from -r ./requirements.txt (line 9)) (3.1.2)
Requirement already satisfied: glob2==0.6 in ./.venv/lib/python3.11/site-packages (from -r ./requirements.txt (line 10)) (0.6)
Requirement already satisfied: MarkupSafe>=2.0 in ./.venv/lib/python3.11/site-packages (from Jinja2==3.1.2->-r ./requirements.txt (line 9)) (2.1.5)
Quit with deactivate command...
=== generate docker compose configuration centos-kerberos.local ===
=== copy template directory to ./build-template to ./build-centos-kerberos.local ===
=== generate template configuration for ./build ===
Traceback (most recent call last):
  File "/home/elfmacs/kerberos-docker/./script/generate_from_template.py", line 112, in <module>
    for template_path in glob2.glob(f"./{build_name}/**/*.template", recursive=True):
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/elfmacs/kerberos-docker/.venv/lib/python3.11/site-packages/glob2/impl.py", line 60, in glob
    return list(self.iglob(pathname, with_matches, include_hidden,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/elfmacs/kerberos-docker/.venv/lib/python3.11/site-packages/glob2/impl.py", line 126, in _iglob
    for dirname, dir_groups in dirs:
  File "/home/elfmacs/kerberos-docker/.venv/lib/python3.11/site-packages/glob2/impl.py", line 127, in _iglob
    for name, groups in self.resolve_pattern(dirname, basename,
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/elfmacs/kerberos-docker/.venv/lib/python3.11/site-packages/glob2/impl.py", line 186, in resolve_pattern
    return fnmatch.filter(names, pattern, norm_paths, case_sensitive, sep)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/elfmacs/kerberos-docker/.venv/lib/python3.11/site-packages/glob2/fnmatch.py", line 87, in filter
    match = _compile_pattern(pat, case_sensitive)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/elfmacs/kerberos-docker/.venv/lib/python3.11/site-packages/glob2/fnmatch.py", line 80, in _compile_pattern
    return re.compile(res, flags).match
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 227, in compile
    return _compile(pattern, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_compiler.py", line 743, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 980, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 841, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 6
make: *** [Makefile:40: gen-conf] Error 1

**Comment by TontonJambon** [comment]
I ran into the same issue
Basically it is a known issues with glob2

Replacing it with glob works:

```
diff --git a/script/generate_from_template.py b/script/generate_from_template.py
index c9941cc..a79af3f 100755
--- a/script/generate_from_template.py
+++ b/script/generate_from_template.py
@@ -16,7 +16,7 @@ import sys
 import re
 import shutil
 
-import glob2
+import glob
 import jinja2
 
 def read_context(file_path):
@@ -109,7 +109,7 @@ if __name__ == "__main__":
     shutil.copytree("./build-template/services", f"./{build_name}/services")
     shutil.copyfile("./build-template/docker-compose.yml.template", f"./{build_name}/docker-compose.yml.template")
     print("=== generate template configuration for ./build ===")
-    for template_path in glob2.glob(f"./{build_name}/**/*.template", recursive=True):
+    for template_path in glob.glob(f"./{build_name}/**/*.template", recursive=True):
         if not os.path.isfile(template_path):
             continue
         print(f"render {template_path}")
```
