### ISSUE TITLE
jinja2.exceptions.UndefinedError: 'NETWORK_CONTAINER' is undefined

### ISSUE THREAD

**Issue by pablote** [criteo/kerberos-docker#2]
I've just cloned the repo to test it out, run `make install` and I'm getting that error, is there a step I'm missing? thanks!

full log:
```
Running virtualenv with interpreter /Users/pablo/.pyenv/shims/python3
Using base prefix '/Users/pablo/.pyenv/versions/3.6.6'
New python executable in /Users/pablo/Documents/work/projects/forks/kerberos-docker/env/bin/python3
Not overwriting existing python script /Users/pablo/Documents/work/projects/forks/kerberos-docker/env/bin/python (you must use /Users/pablo/Documents/work/projects/forks/kerberos-docker/env/bin/python3)
Installing setuptools, pip, wheel...done.
Requirement already up-to-date: pip in ./env/lib/python3.6/site-packages (19.0.3)
Requirement already satisfied: Jinja2==2.8 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 9)) (2.8)
Requirement already satisfied: glob2==0.6 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 10)) (0.6)
Requirement already satisfied: MarkupSafe in ./env/lib/python3.6/site-packages (from Jinja2==2.8->-r requirements.txt (line 9)) (1.1.1)
Quit with deactivate command...
=== get environment variables ===
./script/get-env.sh: line 16: envsubst: command not found
...KO
=== generate docker compose configuration ===
render docker-compose.yml.template
Traceback (most recent call last):
  File "./script/generate_from_template.py", line 103, in <module>
    render("docker-compose.yml.template", context)
  File "./script/generate_from_template.py", line 76, in render
    ).get_template(filename).render(context)
  File "/Users/pablo/Documents/work/projects/forks/kerberos-docker/env/lib/python3.6/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/pablo/Documents/work/projects/forks/kerberos-docker/env/lib/python3.6/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/pablo/Documents/work/projects/forks/kerberos-docker/env/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "docker-compose.yml.template", line 4, in top-level template code
    {% set prefix_ip = '.'.join((NETWORK_CONTAINER.split('.')[:3])) %}
  File "/Users/pablo/Documents/work/projects/forks/kerberos-docker/env/lib/python3.6/site-packages/jinja2/environment.py", line 408, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'NETWORK_CONTAINER' is undefined
working directory: /Users/pablo/Documents/work/projects/forks/kerberos-docker
cp: .build-example-com/.env.values and .env.values are identical (not copied).
cp: docker-compose.yml: No such file or directory
Switch to project example-com
.env.values -> .build-example-com/.env.values
docker-compose.yml -> .build-example-com/docker-compose.yml
working directory: /Users/pablo/Documents/work/projects/forks/kerberos-docker/.build-example-com
=== pre-build docker image 'minimal-' ===
invalid argument "minimal-" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
make: *** [pre-build] Error 125

```

**Comment by pablote** [comment]
Nevermind, I just found the problem and fixed it. I'm running on a mac, and `gettext` from brew not only needs to be installed, it's also necessary to manually override the mac included version of it, which doesn't include the `envsubst` command.

**Comment by glegoux** [comment]
Hello Pablo,
Thanks to have raised up this issue. I could stop as soon as possible if this type of error appeared. I am happy to see that the project works well on Mac OS. Don't hesitate to give other feedback to improve user experience.

**Comment by kannangce** [comment]
> Nevermind, I just found the problem and fixed it. I'm running on a mac, and `gettext` from brew not only needs to be installed, it's also necessary to manually override the mac included version of it, which doesn't include the `envsubst` command.

This saved a lot of my time. Thank you...

**Comment by REVProfumo** [comment]
By default, the command `envsubst` is missing on macOS M1. 
For me, what worked was to install `gettext` that includes this command with the following:
```
brew install gettext
brew link --force gettext 
```
The file that was posing problems was `./script/gen-env.sh`
